[project]
name = "certificates-generator-module"
version = "0.1.0"
description = "Description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "qrcode>=8.2",
    "reportlab>=4.4.1",
]
